name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: netstat_continuous

permissions:
  contents: write # This is crucial for creating releases and uploading assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Build Release Binary
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          strip target/x86_64-unknown-linux-gnu/release/${{ env.BINARY_NAME }}

      - name: Create Release and Upload Asset
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          # Create release
          gh release create "$TAG_NAME" \
            --title "Release $TAG_NAME" \
            --notes "Release $TAG_NAME" \
            --repo "${{ github.repository }}"

          # Upload binary
          gh release upload "$TAG_NAME" \
            target/x86_64-unknown-linux-gnu/release/${{ env.BINARY_NAME }} \
            --name "${{ env.BINARY_NAME }}-linux-x64" \
            --repo "${{ github.repository }}"

          